### ISSUE TITLE
calculating threshold vectors

### ISSUE THREAD

**Issue by liorella** [jarzebski/Arduino-MPU6050#1]
Hi Korneliusz,

in MPU6050.cpp, lines 571-574 we have the following code:

    // Calculate threshold vectors
    th.XAxis = sqrt((sigmaX / 50) - (dg.XAxis * dg.XAxis));
    th.YAxis = sqrt((sigmaY / 50) - (dg.YAxis * dg.YAxis));
    th.ZAxis = sqrt((sigmaZ / 50) - (dg.ZAxis * dg.ZAxis));

should the numbers 50 be replaced by the variable "samples"?

Good day,

Lior

**Comment by specialsenja** [comment]
do you know how to get this equation?
is this variance equation?

**Comment by jarzebski** [comment]
fix in master
