### ISSUE TITLE
ESP32 Arduino IDE values increase every time I move the board.

### ISSUE THREAD

**Issue by therealwokewok** [jarzebski/Arduino-MPU6050#10]
Pitch and roll consistently go up.  As in it += each loop.  The yaw presents a 0.00 every loop no matter what.  Any tips on making this work in this environment?

**Comment by J3r3Xy** [comment]
It is called drifting, is very common in gyroscopes. To have reliable data in the long run you should use a fusion algorithm (see [here](https://www.digikey.com/en/articles/techzone/2018/jan/apply-sensor-fusion-to-accelerometers-and-gyroscopes)). For the yaw not changing, try a different range setting
