### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by fbiego** [jarzebski/Arduino-MPU6050#19]
What are the units of acceleration and gyroscope for both raw and normalize?

**Comment by J3r3Xy** [comment]
Unit for normalized acceleration is in g (1g = 9.81m/s/s), for raw acceleration is the reading from the sensor and depends on the selected range (divide by 2^15/range to get m/s/s).
Unit for normalized gyroscope is deg/s and for raw gyro is the reading from the sensor and depends on the selected range(dived by 2^15/range to get deg/s)
