### ISSUE TITLE
I got an error for free falling

### ISSUE THREAD

**Issue by anilshetty538** [jarzebski/Arduino-MPU6050#3]
Arduino: 1.8.1 (Windows 7), Board: "Arduino/Genuino Uno"

C:\Users\Dell\Documents\Arduino\free_fal\free_fal.ino: In function 'void setup()':

free_fal:16: error: 'class MPU6050' has no member named 'begin'

   while(!mpu.begin(MPU6050_SCALE_2000DPS, MPU6050_RANGE_16G))

              ^

free_fal:16: error: 'MPU6050_SCALE_2000DPS' was not declared in this scope

   while(!mpu.begin(MPU6050_SCALE_2000DPS, MPU6050_RANGE_16G))

                    ^

free_fal:16: error: 'MPU6050_RANGE_16G' was not declared in this scope

   while(!mpu.begin(MPU6050_SCALE_2000DPS, MPU6050_RANGE_16G))

                                           ^

free_fal:22: error: 'class MPU6050' has no member named 'setAccelPowerOnDelay'

   mpu.setAccelPowerOnDelay(MPU6050_DELAY_3MS);

       ^

free_fal:22: error: 'MPU6050_DELAY_3MS' was not declared in this scope

   mpu.setAccelPowerOnDelay(MPU6050_DELAY_3MS);

                            ^

free_fal:24: error: 'class MPU6050' has no member named 'setIntFreeFallEnabled'

   mpu.setIntFreeFallEnabled(true);

       ^

free_fal:28: error: 'MPU6050_DHPF_5HZ' was not declared in this scope

   mpu.setDHPFMode(MPU6050_DHPF_5HZ);

                   ^

free_fal:30: error: 'class MPU6050' has no member named 'setFreeFallDetectionThreshold'

   mpu.setFreeFallDetectionThreshold(17);

       ^

free_fal:31: error: 'class MPU6050' has no member named 'setFreeFallDetectionDuration'

   mpu.setFreeFallDetectionDuration(2);  

       ^

C:\Users\Dell\Documents\Arduino\free_fal\free_fal.ino: In function 'void checkSettings()':

free_fal:61: error: 'class MPU6050' has no member named 'getIntFreeFallEnabled'

   Serial.println(mpu.getIntFreeFallEnabled() ? "Enabled" : "Disabled");

                      ^

free_fal:64: error: 'class MPU6050' has no member named 'getFreeFallDetectionThreshold'

   Serial.println(mpu.getFreeFallDetectionThreshold());

                      ^

free_fal:67: error: 'class MPU6050' has no member named 'getFreeFallDetectionDuration'

   Serial.println(mpu.getFreeFallDetectionDuration());

                      ^

free_fal:73: error: 'MPU6050_CLOCK_EXTERNAL_19MHZ' was not declared in this scope

     case MPU6050_CLOCK_EXTERNAL_19MHZ: Serial.println("PLL with external 19.2MHz reference"); break;

          ^

free_fal:74: error: 'MPU6050_CLOCK_EXTERNAL_32KHZ' was not declared in this scope

     case MPU6050_CLOCK_EXTERNAL_32KHZ: Serial.println("PLL with external 32.768kHz reference"); break;

          ^

free_fal:78: error: 'MPU6050_CLOCK_INTERNAL_8MHZ' was not declared in this scope

     case MPU6050_CLOCK_INTERNAL_8MHZ:  Serial.println("Internal 8MHz oscillator"); break;

          ^

free_fal:82: error: 'class MPU6050' has no member named 'getRange'

   switch(mpu.getRange())

              ^

free_fal:84: error: 'MPU6050_RANGE_16G' was not declared in this scope

     case MPU6050_RANGE_16G:            Serial.println("+/- 16 g"); break;

          ^

free_fal:85: error: 'MPU6050_RANGE_8G' was not declared in this scope

     case MPU6050_RANGE_8G:             Serial.println("+/- 8 g"); break;

          ^

free_fal:86: error: 'MPU6050_RANGE_4G' was not declared in this scope

     case MPU6050_RANGE_4G:             Serial.println("+/- 4 g"); break;

          ^

free_fal:87: error: 'MPU6050_RANGE_2G' was not declared in this scope

     case MPU6050_RANGE_2G:             Serial.println("+/- 2 g"); break;

          ^

free_fal:91: error: 'class MPU6050' has no member named 'getAccelOffsetX'

   Serial.print(mpu.getAccelOffsetX());

                    ^

free_fal:93: error: 'class MPU6050' has no member named 'getAccelOffsetY'

   Serial.print(mpu.getAccelOffsetY());

                    ^

free_fal:95: error: 'class MPU6050' has no member named 'getAccelOffsetZ'

   Serial.println(mpu.getAccelOffsetZ());

                      ^

free_fal:98: error: 'class MPU6050' has no member named 'getAccelPowerOnDelay'

   switch(mpu.getAccelPowerOnDelay())

              ^

free_fal:100: error: 'MPU6050_DELAY_3MS' was not declared in this scope

     case MPU6050_DELAY_3MS:            Serial.println("3ms"); break;

          ^

free_fal:101: error: 'MPU6050_DELAY_2MS' was not declared in this scope

     case MPU6050_DELAY_2MS:            Serial.println("2ms"); break;

          ^

free_fal:102: error: 'MPU6050_DELAY_1MS' was not declared in this scope

     case MPU6050_DELAY_1MS:            Serial.println("1ms"); break;

          ^

free_fal:103: error: 'MPU6050_NO_DELAY' was not declared in this scope

     case MPU6050_NO_DELAY:             Serial.println("0ms"); break;

          ^

C:\Users\Dell\Documents\Arduino\free_fal\free_fal.ino: In function 'void loop()':

free_fal:111: error: 'Vector' was not declared in this scope

   Vector rawAccel = mpu.readRawAccel();

   ^

free_fal:112: error: 'Activites' was not declared in this scope

   Activites act = mpu.readActivites();

   ^

free_fal:114: error: 'act' was not declared in this scope

   Serial.print(act.isFreeFall);

                ^

exit status 1
'class MPU6050' has no member named 'begin'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by fbiego** [comment]
Hi,
You have to delete the existing MPU6050 library
