### ISSUE TITLE
Units per deg/sec?

### ISSUE THREAD

**Issue by Isaac96** [jarzebski/Arduino-MPU6050#6]
I am making a balancing robot and I need to figure out how many units per deg/sec  the 
     `mpu.readNormalizeGyro();`
function outputs. I have the gyro configured using 
`mpu.begin(MPU6050_SCALE_500DPS, MPU6050_RANGE_2G)`
Could anyone tell me the range? 
Thank you!

**Comment by J3r3Xy** [comment]
`mpu.readNormalizeGyro()` returns the angular speed in degrees per second. `MPU6050_SCALE_500DPS` means that the max speed will be 500 deg/s (+500 for CW rotation and -500 for CCW rotation if I remember correctly)
