### ISSUE TITLE
calibrateGyro uses fixed constant of 50

### ISSUE THREAD

**Issue by filmo** [jarzebski/Arduino-MPU6050#9]
```    
// Calculate threshold vectors
    th.XAxis = sqrt((sigmaX / 50) - (dg.XAxis * dg.XAxis));
    th.YAxis = sqrt((sigmaY / 50) - (dg.YAxis * dg.YAxis));
    th.ZAxis = sqrt((sigmaZ / 50) - (dg.ZAxis * dg.ZAxis));
```
I think the '50' should be replaced with the parameter 'samples' passed into calibrateGyro, otherwise if samples != 50, then these thresholds will be incorrect.

**Comment by specialsenja** [comment]
do you know how to get this equation?
is this variance equation?

**Comment by jarzebski** [comment]
fixed in master
